// Auto-generated image mapping from menu pics folder
const getMenuItemImage = (itemName: string): string => {
  const imageMap: { [key: string]: string } = {
    '70 MM Dosa (Dine in Only)': '/images/menu pics/Onion_Dosa.jpeg',
    'Aloo Gobi Masala': '/images/menu pics/Aloo_Gobi_Masala.jpeg',
    'Amaravati Chicken Curry': '/images/menu pics/Amaravati_Chicken_Curry.jpeg',
    'Amaravati Mutton Curry': '/images/menu pics/Amaravati_Mutton_Curry.jpeg',
    'Andhra Chicken Curry': '/images/menu pics/Ulavacharu_Chicken_Curry.jpg',
    'Apollo Fish': '/images/menu pics/Apollo_Fish.jpeg',
    'Boneless Chicken Biryani': '/images/menu pics/Boneless_Chicken_Biryani.jpeg',
    'Boneless Mutton Biryani': '/images/menu pics/Boneless_Mutton_Biryani.jpeg',
    'Butter Chicken': '/images/menu pics/Butter_Chicken.jpeg',
    'Butter Naan': '/images/menu pics/Butter_Naan.jpeg',
    'Chicken 555': '/images/menu pics/Chicken_555.jpeg',
    'Chicken Fried Rice': '/images/menu pics/Chicken_Fried_Rice.jpeg',
    'Chicken Hakka Noodles': '/images/menu pics/Chicken_Hakka_Noodles.jpeg',
    'Chicken Lollipops (Dry) {4}': '/images/menu pics/Chicken_65_Dry.jpeg',
    'Chicken Majestic': '/images/menu pics/Kothimeera_Kodi_Cilantro_chicken.jpg',
    'Chicken Manchurian': '/images/menu pics/Chicken_Manchurian_Wet.jpeg',
    'Chicken Schezwan Fried Rice': '/images/menu pics/Chicken_Schezwan_Fried_Rice.jpeg',
    'Chicken Shahi Korma': '/images/menu pics/Chicken_Shahi_Khorma.jpeg',
    'Chicken Tikka Kabab': '/images/menu pics/Chicken_Tikka_Kabab.jpeg',
    'Chicken Tikka Masala': '/images/menu pics/Chicken_Tikka_Masala.jpeg',
    'Chicken Vindaloo': '/images/menu pics/Chicken_Vindaloo.jpeg',
    'Chilli Chicken': '/images/menu pics/Chilli_Chicken.jpeg',
    'Chilli Fish': '/images/menu pics/Chilli_Fish.jpeg',
    'Chilli Idli': '/images/menu pics/Chilli_Idli.jpeg',
    'Chilli Shrimp': '/images/menu pics/Chilli_Shrimp.jpeg',
    'Crispy Corn': '/images/menu pics/Corn_Manchurian.jpeg',
    'Dal Makhani': '/images/menu pics/Dal_Makhani.jpeg',
    'Dal Tadka': '/images/menu pics/Dal_Tadka.jpeg',
    'Egg Biryani': '/images/menu pics/Egg_Biryani.jpeg',
    'Fish Biryani': '/images/menu pics/Fish_Biryani.jpeg',
    'Fish Masala': '/images/menu pics/Fish_Masala.jpeg',
    'Fish Pulusu': '/images/menu pics/Fish_Pulusu.jpg',
    'Garlic Naan': '/images/menu pics/Garlic_Naan.jpeg',
    'Gobi Manchurian': '/images/menu pics/Gobi_Manchurian.jpeg',
    'Gongura Chicken Dum Biryani': '/images/menu pics/Gongura_Chicken_Dum_Biryani.jpeg',
    'Gongura Mutton Curry': '/images/menu pics/Gongura_Mutton_Curry.jpeg',
    'Gulab Jamun': '/images/menu pics/Gulab_Jamu.jpeg',
    'Hyderabad Chicken Curry': '/images/menu pics/Hyderabad_Chicken_Curry.jpeg',
    'Hyderabad Goat Curry': '/images/menu pics/Karaikudi_Goat_Curry.jpeg',
    'Hyderabadi Chicken Dum Biryani': '/images/menu pics/Hyderabadi_Chicken_Dum_Biryani.jpeg',
    'Hyderabadi Goat Dum Biryani': '/images/menu pics/Hyderbadi_Goat_Dum_Biryani_-_Single_Pack_-_24_oz.jpeg',
    'Hyderabadi Veg Dum Biryani': '/images/menu pics/Hyderabadi_Veg_Dum_Biryani.jpeg',
    'Idli {2}': '/images/menu pics/Idli_2.jpeg',
    'Kadai Chicken': '/images/menu pics/Kadai_Chicken.jpeg',
    'Kadai Paneer': '/images/menu pics/Kadai_Paneer.jpeg',
    'Karaikudi Chicken': '/images/menu pics/Karaikudi_Chicken.jpeg',
    'Lamb Korma': '/images/menu pics/Kadai_Lamb.jpeg',
    'Lamb Rogan Gosh': '/images/menu pics/Lamb_Rogan_Josh.jpeg',
    'Lamb Saag': '/images/menu pics/Lamb_Saag.jpeg',
    'Malai Kofta': '/images/menu pics/Malai_Kofta.jpeg',
    'Mango Lassi': '/images/menu pics/Mango_Lassi.jpeg',
    'Masala Dosa': '/images/menu pics/Rava_Masala_Dosa.jpeg',
    'Masala Rice': '/images/menu pics/Masala_Rice.jpg',
    'Medu Vada {2}': '/images/menu pics/Medu_Vada_2.jpeg',
    'Mutton Masala': '/images/menu pics/Mutton_Masala.jpeg',
    'Mutton Pepper Fry (Bone-In)': '/images/menu pics/Mutton_Pepper_Fry_Bone-In.jpeg',
    'Mutton Roast (Boneless)': '/images/menu pics/Mutton_Roast_Boneless.jpeg',
    'Mutton Vindaloo (Goat)': '/images/menu pics/Mutton_Vindaloo.jpeg',
    'Nalli Gosht Biryani': '/images/menu pics/Temper_Veg_Dum_Biryani.jpeg',
    'Natukodi Fry Biryani': '/images/menu pics/Natukodi_Fry_Biryani.jpeg',
    'Onion Kulcha': '/images/menu pics/Onion_Kulcha.jpeg',
    'Paneer Biryani': '/images/menu pics/Paneer_Biryani.jpeg',
    'Paneer Tikka Kabab': '/images/menu pics/Paneer_Tikka_Kabab.jpeg',
    'Paneer Tikka Masala': '/images/menu pics/Paneer_Tikka_Dosa.jpeg',
    'Plain Dosa': '/images/menu pics/Plain_Dosa.jpeg',
    'Plain Naan': '/images/menu pics/Plain_Naan.jpeg',
    'Plain Uthappam': '/images/menu pics/Plain_Uthappam.jpeg',
    'Pulav Rice': '/images/menu pics/Veg_Schezwan_Fried_Rice.jpeg',
    'Rice': '/images/menu pics/Rice.jpeg',
    'Shrimp Iguru': '/images/menu pics/Guntur_Shrimp.png',
    'Sweet Lassi': '/images/menu pics/Chicken_Sweet_Corn_Soup.jpeg',
    'Tandoori Chicken (Full)': '/images/menu pics/Full_Tandoori_Chicken.jpeg',
    'Tandoori Chicken (Half)': '/images/menu pics/Half_Tandoori_Chicken.jpeg',
    'Tandoori Pomfret (Fish)': '/images/menu pics/Tandoori_Pomfret.jpg',
    'Tandoori Roti': '/images/menu pics/Tandoori_Roti.jpeg',
    'Ulavacharu Chicken Dum Biryani': '/images/menu pics/Avakai_Chicken_Dum_Biryani_-_Single_Pack_-_24_oz.jpeg',
    'Ulavacharu Goat Curry': '/images/menu pics/Ulavacharu_Goat_Curry.jpeg',
    'Veg Fried Rice': '/images/menu pics/Veg_Fried_Rice.jpeg',
    'Veg Hakka Noodles': '/images/menu pics/Veg_Hakka_Noodles.jpeg',
    'Veg Manchurian (Wet)': '/images/menu pics/Veg_Manchurian.jpeg',
    'Vegetable Korma': '/images/menu pics/Vegetable_Khorma.jpeg',
    'Vegetable Samosa {2}': '/images/menu pics/Sambar_Idli_2.jpeg',
  };

  // Return mapped image or default
  return imageMap[itemName] || '/images/Food Pic/Hero Shot.png';
};

export default getMenuItemImage;
